spring.application.name=Weather-App
server.port=8082
weather.api.key=2c72a75984e947fe8c380721262309
weather.api.url=https://api.weatherapi.com/v1/current.json
weather.api.forecast.url=https://api.weatherapi.com/v1/forecast.json